### ISSUE TITLE
Install via composer

### ISSUE THREAD

**Issue by misilot** [mjordan/islandora_workbench_integration#14]
Is it possible to have this package published to Packagist so it can be installed via composer?

Thanks!

**Comment by mjordan** [comment]
Yes, it's possible, but in the meantime adding this to your composer.json should work: 

```
 "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/mjordan/islandora_workbench_integration.git"
        }
  ]

"require": {
        "mjordan/islandora_workbench_integration": "dev-main",
  }
```

**Comment by misilot** [comment]
It's on Packagist now https://packagist.org/packages/mjordan/islandora_workbench_integration

Thanks @mjordan!

**Comment by mjordan** [comment]
Thanks for your help. Github is not letting me push at the moment ("Password authentication is temporarily disabled as part of a brownout.") but I have removed the 'dev-main' from the docker command as discussed in slack and it worked.
